<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1530013831443" stop="1530013860663" version="1.4.4">
    <name>Default suite</name>
    <title>Default suite : Default test</title>
    <test-cases>
        <test-case start="1530013833031" stop="1530013860036" status="broken">
            <name>tc14250_VerifyAnEDDChangesToAwaitingApproval[Run1,{Password=RankGroup02, Loss Value=1, CustomerNumber=1955155541, Reason=Periodic Review, TestCaseID=TC14250, UserName=SQSEDD}]</name>
            <title>Test 14250</title>
            <description type="text">Verify an EDD changes to Awaiting Approval when user doesn’t have correct authorisation limit </description>
            <failure>
                <message>NullPointerException: null</message>
                <stack-trace>java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
	at org.openqa.selenium.support.ui.FluentWait.&lt;init&gt;(FluentWait.java:96)
	at org.openqa.selenium.support.ui.WebDriverWait.&lt;init&gt;(WebDriverWait.java:72)
	at org.openqa.selenium.support.ui.WebDriverWait.&lt;init&gt;(WebDriverWait.java:46)
	at com.generic.BaseTest.initializeWebEnvironment(BaseTest.java:81)
	at com.scripts.EDD.TC14250_VerifyAnEDDChangesToAwaitingApprovalWhenUserDoesntHaveCorrectAuthorisationLimit.setEnviorment(TC14250_VerifyAnEDDChangesToAwaitingApprovalWhenUserDoesntHaveCorrectAuthorisationLimit.java:30)
	at com.scripts.EDD.TC14250_VerifyAnEDDChangesToAwaitingApprovalWhenUserDoesntHaveCorrectAuthorisationLimit.tc14250_VerifyAnEDDChangesToAwaitingApproval(TC14250_VerifyAnEDDChangesToAwaitingApprovalWhenUserDoesntHaveCorrectAuthorisationLimit.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="D90D3CQ1"/>
                <label name="thread" value="10068@D90D3CQ1.main"/>
            </labels>
        </test-case>
        <test-case start="1530013833031" stop="1530013860036" status="broken">
            <name>tc14250_VerifyAnEDDChangesToAwaitingApproval[Run1,{Password=RankGroup02, Loss Value=1, CustomerNumber=1955155541, Reason=Periodic Review, TestCaseID=TC14250, UserName=SQSEDD}]</name>
            <title>Test 14250</title>
            <description type="text">Verify an EDD changes to Awaiting Approval when user doesn’t have correct authorisation limit </description>
            <failure>
                <message>NullPointerException: null</message>
                <stack-trace>java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
	at org.openqa.selenium.support.ui.FluentWait.&lt;init&gt;(FluentWait.java:96)
	at org.openqa.selenium.support.ui.WebDriverWait.&lt;init&gt;(WebDriverWait.java:72)
	at org.openqa.selenium.support.ui.WebDriverWait.&lt;init&gt;(WebDriverWait.java:46)
	at com.generic.BaseTest.initializeWebEnvironment(BaseTest.java:81)
	at com.scripts.EDD.TC14250_VerifyAnEDDChangesToAwaitingApprovalWhenUserDoesntHaveCorrectAuthorisationLimit.setEnviorment(TC14250_VerifyAnEDDChangesToAwaitingApprovalWhenUserDoesntHaveCorrectAuthorisationLimit.java:30)
	at com.scripts.EDD.TC14250_VerifyAnEDDChangesToAwaitingApprovalWhenUserDoesntHaveCorrectAuthorisationLimit.tc14250_VerifyAnEDDChangesToAwaitingApproval(TC14250_VerifyAnEDDChangesToAwaitingApprovalWhenUserDoesntHaveCorrectAuthorisationLimit.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="D90D3CQ1"/>
                <label name="thread" value="10068@D90D3CQ1.main"/>
            </labels>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="TestNG"/>
        <label name="language" value="JAVA"/>
    </labels>
</ns2:test-suite>
